### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by bloha** [rajce-client/rajce-sdk#1]
# v1 Roadmap

## Authorization
- [ ] Implement user login
- [ ] Implement user logout
- [ ] Implement user settings update
- [ ] Implement user registration
- [ ] Implement user deletion

## Browsing
- [ ] Implement search results generator
- [ ] Implement tag results generator
- [ ] Implement user albums generator
- [ ] Implement favorite albums generator
- [ ] Implement categorized albums generator

## Uploading
- [ ] Implement album creation
- [ ] Implement album deletion
- [ ] Implement album settings update
- [ ] Implement media file uploading
